Add openweather virtual schema
exasol/openweather-virtual-schema pull request #1
Opened 2020-09-24 15:39 UTC by LennartAtExasol

2020-09-28 12:53 UTC, AnastasiiaSergienko requested changes
Nice work! Let's work on code improvements now

2020-09-28 12:53 UTC, AnastasiiaSergienko commented on openweather-virtual-schema.sql
> +import json
It would be nice to divide the SQL and Python code. You can add the SQL commands to the user guide and place the python script in a separate file

2020-09-28 12:53 UTC, AnastasiiaSergienko commented on openweather-virtual-schema.sql
> +    '''Logger init end'''
You can extract a function here and give it a clear name instead of adding commens

2020-09-28 12:53 UTC, AnastasiiaSergienko commented on openweather-virtual-schema.sql
> +    rootLogger.setLevel(logging.WARNING)                                                  #--Set logging level
The comments in not needed here, it's clear from the code that you set a logging level :)

2020-09-28 12:53 UTC, AnastasiiaSergienko commented on openweather-virtual-schema.sql
> +    socketHandler = PlainTextTcpHandler('192.168.177.83', 3333)                         #--Set logging IP and port here
They shouldn't be hardcoded here. They can come as parameters to the script

2020-09-28 12:53 UTC, AnastasiiaSergienko commented on openweather-virtual-schema.sql
> +    root = json.loads(request)
It's better to rename the root -> request_as_json or something like this

2020-09-28 12:53 UTC, AnastasiiaSergienko commented on openweather-virtual-schema.sql
> +    if root["type"] == "createVirtualSchema":
make a variable reuest_type  from `root["type"] `  and use it in the if-else statement

2020-09-28 12:53 UTC, AnastasiiaSergienko commented on openweather-virtual-schema.sql
> +def handleCreateVSchema(root, logger):
Please, follow the naming convention: https://visualgit.readthedocs.io/en/latest/pages/naming_convention.html

Check the names through the file

2020-09-28 12:53 UTC, AnastasiiaSergienko commented on openweather-virtual-schema.sql
> +def handleCreateVSchema(root, logger):
```suggestion
def handle_create_virtual_schema(root, logger):
```

2020-09-28 12:53 UTC, AnastasiiaSergienko commented on openweather-virtual-schema.sql
> +    res = {"type": "createVirtualSchema",
Please, don't abbreviate the variable names. res -> result

2020-09-28 12:53 UTC, AnastasiiaSergienko commented on openweather-virtual-schema.sql
> +    weather_forcast = {  "name": "FORECAST",
forcast -> forecast

2020-09-28 12:53 UTC, AnastasiiaSergienko commented on openweather-virtual-schema.sql
> +    logger.info('>>>>PUSHDOWN<<<<')                                         #DEBUG
Remove the comments please

2020-09-28 12:53 UTC, AnastasiiaSergienko commented on openweather-virtual-schema.sql
> +    def current_weather_sql(host, api_key, method, parameters):
Please don't create functions inside functions. Make the class flat

2020-09-28 12:53 UTC, AnastasiiaSergienko commented on openweather-virtual-schema.sql
> +        if filter_name == 'CITY_NAME':
This long if-else statement contains a lot of duplication. You can create a map with the mapping of the column name and the API value (e.g.  CITY_NAME=q, LONGITUDE=lon etc) and union the if cases with the same type (float, int) and insert the key value as a variable from the map based on the filter_name

2020-09-28 12:53 UTC, AnastasiiaSergienko commented on openweather-virtual-schema.sql
> +    def sql_builder(API_URL, API_KEY, root, logger):
The method names should start from a verb

2020-09-28 12:53 UTC, AnastasiiaSergienko commented on openweather-virtual-schema.sql
> +                #-- Handle zip code requests
It's always better to extract a method with a good name than writing a comment. Also the inner elseif should go to its own method as it's hard to read this code here

2020-10-07 09:39 UTC, LennartAtExasol commented on openweather-virtual-schema.sql
> +def handleCreateVSchema(root, logger):
Thanks, lol I took those namings over from André 😁  Shame shame shame! 🔔

2020-10-08 07:07 UTC, LennartAtExasol commented on openweather-virtual-schema.sql
> +        if filter_name == 'CITY_NAME':
Pretty obvious improvement - should have done it this way in the first place. Reduced code length, increased readability - love it!

2020-10-08 07:10 UTC, LennartAtExasol commented on openweather-virtual-schema.sql
> +    if root["type"] == "createVirtualSchema":
It saves a couple of characters but why is this beneficial?

2020-10-08 08:01 UTC, LennartAtExasol commented on openweather-virtual-schema.sql
> +def handleCreateVSchema(root, logger):
Interestingly when working with pythons logging package there are methods like "setFormatter" which also don't comply to the convention - I wonder why that is.

Changes it anyway :)

2020-10-08 10:28 UTC, LennartAtExasol commented on openweather-virtual-schema.sql
> +                #-- Handle zip code requests
lets talk about this

2020-10-08 10:28 UTC, LennartAtExasol commented on openweather-virtual-schema.sql
> +import json
lets talk about this

2020-10-12 12:44 UTC, AnastasiiaSergienko commented on openweather-virtual-schema.sql
> +import json
You can check this as an example: 
https://github.com/exasol/data-science-examples/pull/10/files#diff-484d3655bc619ceef5fd8d9ed8c1c30d

2020-10-12 13:29 UTC, AnastasiiaSergienko requested changes

2020-10-12 13:29 UTC, AnastasiiaSergienko commented on openweather-virtual-schema.sql
> +----Cleaning up
I think if we want to support and maintain it, we definitely need an integration test for it.

2020-10-12 13:29 UTC, AnastasiiaSergienko commented on openweather-virtual-schema.sql
> +DROP SCHEMA openweather_vs_scripts CASCADE;
These lines shouldn't be here in the final version. I still suggest to extract the python code and move the SQL part to the user guide

2020-10-12 13:29 UTC, AnastasiiaSergienko commented on openweather-virtual-schema.sql
> +def initialize_logger(ip, port, level):
As I'm usually using the OOP paradigm, I suggest creating proper classes for this script, it will help to maintain the project easier.

2020-10-12 13:29 UTC, AnastasiiaSergienko commented on openweather-virtual-schema.sql
> +    LOG_LEVEL = request_json_object['schemaMetadataInfo']['properties']['LOG_LEVEL']
You can make them class constants if you create a class. It improves readability

2020-10-12 13:29 UTC, AnastasiiaSergienko commented on openweather-virtual-schema.sql
> +def initialize_logger(ip, port, level):
Place the methods in the order you call them.  I suppose the adapter_call is an entry, it should come first, and all other methods in the order they appear in the code.

2020-10-12 13:29 UTC, AnastasiiaSergienko commented on openweather-virtual-schema.sql
> +def adapter_call(request):
Python doesn't require to specify the variable types, but it makes life much easier, so I recommend always declare the variable types 
https://www.python.org/dev/peps/pep-0612/#:~:text=A%20parameter%20specification%20variable%20is,TypeVar.&text=The%20runtime%20should%20accept%20bounds,the%20declaration%20just%20as%20typing.

2020-10-12 13:29 UTC, AnastasiiaSergienko commented on openweather-virtual-schema.sql
> +def adapter_call(request):
Also would be nice to add docs to all public methods and classes

2020-10-12 13:29 UTC, AnastasiiaSergienko commented on openweather-virtual-schema.sql
> +    if request_type == "getCapabilities":
should it be `elif` too?

2020-10-12 13:29 UTC, AnastasiiaSergienko commented on openweather-virtual-schema.sql
> +    API_URL = 'https://api.openweathermap.org/data/2.5/'
You define it too far away from the place where you really use it. The best solution will be a class constant. Otherwise, it should go to the place where it's used for the first time. Also, check other similar places

2020-10-12 13:29 UTC, AnastasiiaSergienko commented on openweather-virtual-schema.sql
> +    # -- Check if expressions are reversed
Use a doc instead of a comment

2020-10-12 13:29 UTC, AnastasiiaSergienko commented on openweather-virtual-schema.sql
> +    if not filter_json.get('right').get('value'):
How about reversing this expression? It will be easier to realize what it's doing and also it removes

2020-10-12 13:29 UTC, AnastasiiaSergienko commented on openweather-virtual-schema.sql
> +    if filter_name in ('CITY_NAME', 'COUNTRY_CODE'):
This if statement is not very readable.  The methods should be extracted for each case

2020-10-12 13:29 UTC, AnastasiiaSergienko commented on openweather-virtual-schema.sql
> +
Remove unnecessary spaces. Also ideally, in the methods, you usually don't need any spaces. If you want to add a space for readability or for highlighting a logical block - it's a clear sign that you need to extract a method there instead of adding spaces

2020-10-12 13:29 UTC, AnastasiiaSergienko commented on openweather-virtual-schema.sql
> +class PlainTextTcpHandler(logging.handlers.SocketHandler):
This duplication can be fixed if you place a class in a separate file and import it

2020-10-12 13:29 UTC, AnastasiiaSergienko commented on openweather-virtual-schema.sql
> +def initialize_logger(ip, port, level):
Also duplication

2020-10-12 13:29 UTC, AnastasiiaSergienko commented on openweather-virtual-schema.sql
> +select * from OPENWEATHER.CURRENT_WEATHER
If you use uppercase for other SQL commands, use it here too, it will look unified

2020-10-12 13:29 UTC, AnastasiiaSergienko commented on openweather-virtual-schema.sql
> +WITH API_KEY = 'd5ea350b0a22f5ba4e4b8f8570bd7c73'
These hardcoded values definitely shouldn't be here when we merge this branch

2020-10-13 06:30 UTC, AnastasiiaSergienko commented
We're missing a license file in this repository

2020-10-14 05:38 UTC, LennartAtExasol commented on openweather-virtual-schema.sql
> +import json
I don't think I like it. This relies on having access to the repo whenever you want to create / re-create the schema. While it might clean up the code it makes the whole solution more fragile. Alternatively the files could reside on BucketFS but that makes deployment way more complex. I'm not really sure it's worth the effort.

2020-10-14 06:01 UTC, LennartAtExasol commented on openweather-virtual-schema.sql
> +def initialize_logger(ip, port, level):
I thought they were supposed to be ordered in an alphabetical manner?

2020-10-14 06:02 UTC, LennartAtExasol commented on openweather-virtual-schema.sql
> +def adapter_call(request):
Wasn't type hinting introduced in python 3.8 and we still run python 3.6? I think I remember running into this issue a couple of times

2020-10-14 08:01 UTC, LennartAtExasol commented on openweather-virtual-schema.sql
> +def initialize_logger(ip, port, level):
How should the order be? First used methods on top or at the bottom?

2020-10-16 07:57 UTC, AnastasiiaSergienko commented on openweather-virtual-schema.sql
> +    def get_current_weather_table_json() -> dict:
I would make it private instead of static.

2020-10-16 07:57 UTC, AnastasiiaSergienko commented on openweather-virtual-schema.sql
> +    def get_current_weather_table_json() -> dict:
```suggestion
    def __get_current_weather_table_json() -> dict:
```

2020-10-16 07:57 UTC, AnastasiiaSergienko commented on openweather-virtual-schema.sql
> +    def get_current_weather_table_json() -> dict:
Same for others

2020-10-16 07:57 UTC, AnastasiiaSergienko commented on openweather-virtual-schema.sql
> +    def build_sql(self):
Every function that is not called from outside of this class should be private

2020-10-16 07:57 UTC, AnastasiiaSergienko commented on openweather-virtual-schema.sql
> +        raise ValueError('F-VS-OWFS-1 Unsupported adapter callback')
This should also go to the AdapterCallHandler as a method so the handler takes a request and decides itself how to handle it

2020-10-20 11:23 UTC, AnastasiiaSergienko submitted a review, later dismissed

2020-10-20 12:14 UTC, merged